apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::902158353355:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-C9XS7TQV06WC
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::902158353355:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-28T18:29:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1594"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ed16f678-af13-4b1d-8d0a-75cca7855776
